version: '3.8'
services:

  backend:
    image: wexin-openai-proxy
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./config:/app/config
      - ./log:/app/log

  frontend:
    image: chatbot-ui
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_HOST=http://backend:8000