version: '3.8'
services:

  backend:
    image: wexin-openai-proxy
    ports:
      - "6000:6000"
    command: uvicorn main:app --host 0.0.0.0 --port 6000
    volumes:
      - ./config:/app/config
      - ./log:/app/log

  frontend:
    image: chatbot-ui
    ports:
      - 3000:3000